=== barzerman/barzer/barzel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.barzer.net/barzel/0.1"
           xmlns:tns="http://www.barzer.net/barzel/0.1"
           elementFormDefault="qualified">

    <xs:complexType name="patNumberType">
    	<xs:attribute name="h" type="xs:decimal"></xs:attribute>
    	<xs:attribute name="l" type="xs:decimal"></xs:attribute>
    	<xs:attribute name="r" type="xs:boolean"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="patList">
    	<xs:choice maxOccurs="unbounded" minOccurs="0">
    		<xs:element name="t" type="xs:string"></xs:element>
    		<xs:element name="n" type="tns:patNumberType" ></xs:element>
    		<xs:element name="p" type="xs:string" ></xs:element>
    		<xs:element name="w"  />
    		<xs:element name="wcls" type="xs:string"  />
    		<xs:element name="list" type="tns:patList"></xs:element>
    		<xs:element name="opt" type="tns:patList"></xs:element>
    		<xs:element name="any" type="tns:patList"></xs:element>
    		<xs:element name="perm" type="tns:patList"></xs:element>
    		<xs:element name="tail" type="tns:patList"></xs:element>
    	</xs:choice>
    </xs:complexType>

    <xs:complexType name="rNumberType">
    	<xs:attribute name="v" type="xs:decimal"></xs:attribute>
    </xs:complexType>    
    
    <xs:complexType name="tranList">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="var" type="xs:string"></xs:element>
            <xs:element name="rn" type="tns:rNumberType"></xs:element>
            <xs:element name="ltrl" type="xs:string"></xs:element>
            <xs:element name="time" type="xs:time"></xs:element>
            <xs:element name="date" type="xs:date"></xs:element>
        </xs:choice>
    </xs:complexType>
    
    <xs:group name="statementGroup">
        <xs:sequence>
            <xs:element name="pat" type="tns:patList" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element name="tran" type="tns:tranList" minOccurs="1" maxOccurs="1"></xs:element>
        </xs:sequence>
    </xs:group>

    <xs:complexType name="statementType">
    	<xs:sequence>
    		<xs:group ref="tns:statementGroup"></xs:group>
    	</xs:sequence>
    </xs:complexType>

    <xs:element name="stmset">
    	<xs:complexType>
    		<xs:sequence maxOccurs="unbounded" minOccurs="0">
    			<xs:element name="stmt" type="tns:statementType"></xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>
</xs:schema>

=== barzerman/barzer/trietest.xml
<?xml version="1.0" encoding="UTF-8"?>
<stmset xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance"
	xmlns="http://www.barzer.net/barzel/0.1">
	<!--
		for some reason xmllint doesn't like this
		xsi:schemaLocation="http://www.barzer.net/barzel/0.1 barzel.xsd">
	-->
	<stmt>
		<pat>
			<any>
				<t>bob</t>
				<t>alice</t>
			</any>
			<t>mama</t>
			<t>myla</t>
			<t>ramu</t>
			<opt>
				<t>s mylom</t>
			</opt>
			<perm>
				<t>foo</t>
				<n />
				<any>
					<n />
				</any>
			</perm>
		</pat>
		<tran>
			<rn v="56" />
		</tran>
	</stmt>
	<stmt>
		<pat>
			<t>6</t>
			<opt>
				<n />
				<wcls>verb</wcls>
			</opt>
		</pat>
		<tran>
			<ltrl>lala</ltrl>
		</tran>
	</stmt>
	<stmt>
		<pat>
			<t>100</t>
			<n />
		</pat>
		<tran>
			<rn v="200" />
		</tran>
	</stmt>
	<stmt>
		<pat>
			<n />
			<t>shit</t>
		</pat>
		<tran>
			<rn v="200" />
		</tran>
	</stmt>
	<!-- this is a simplified version of one of the statements generated by mkxml.py.
		 the original non simplified one was generating almost 400k trie paths.
		 simplified to make profiling a bit more manageable -->
	<stmt>
		<pat>
			<opt>
				<opt>
					<t>SoW</t>
					<n />
					<opt>
						<any>
							<p>$</p>
							<p>_</p>
						</any>
						<t>FLAW</t>
					</opt>
					<t>uSMF</t>
				</opt>

				<any>
					<p>}</p>
					<any>
						<opt>
							<n />
							<t>KAM</t>
							<p>/</p>
							<n h="8743" l="29450" />
						</opt>
						<n />
						<p>!</p>
						<t>lr</t>
					</any>
					<n h="0.452623" l="0.502469" r="true" />
				</any>

				<list>
					<list>
						<t>LkRRJzg</t>
						<n h="26524" l="31602" />
					</list>
					<opt>
						<n h="20070" l="23597" />
						<opt>
							<p>{</p>
							<t>PxukFm</t>
						</opt>
						<n h="1234" l="22393" />
					</opt>
					<list>
						<n />
						<p>+</p>
						<opt>
							<t>YNjFXJuE</t>
							<p>+</p>
						</opt>
						<p>\</p>
					</list>
					<p>\</p>
				</list>
				<n h="0.234674" l="0.717309" r="true" />
			</opt>

			<list>
				<any>
					<t>YeDSZqAgbU</t>
					<opt>
						<list>
							<t>VCPETQBFB</t>
							<p>,</p>
						</list>
						<n h="2810" l="9973" />
						<n />
					</opt>
					<t>qw</t>
					<n h="0.194325" l="0.496656" r="true" />
				</any>

				<list>
					<p>$</p>
					<list>
						<n />
						<p>#</p>
					</list>
					<n h="7686" l="31006" />
					<p>`</p>
					<p>`</p>
					<t>cgqw</t>
				</list>
			</list>
			<opt>
				<p>"</p>
				<opt>
					<any>
						<p>.</p>
						<n />
						<t>eRwwzf</t>
						<list>
							<p>#</p>
							<t>eemHLHhPX</t>
							<p>.</p>
							<p>;</p>
							<t>UOufQLLyhb</t>
						</list>
					</any>
					<opt>
						<n h="0.475731" l="0.603058" r="true" />
						<n h="0.442152" l="0.458857" r="true" />
						<list>
							<t>zXBTBKFAt</t>
							<t>IAh</t>
							<n h="0.266579" l="0.929188" r="true" />
						</list>
						<t>GMXZrBR</t>
						<p>(</p>
						<n h="0.037169" l="0.300429" r="true" />
					</opt>
					<opt>
						<p>\</p>
						<list>
							<t>ePJzmsHu</t>
							<p>_</p>
							<t>uXFCEt</t>
							<t>jwitAqA</t>
							<t>TCUXJVH</t>
						</list>
						<t>RtzUmcWBZd</t>
					</opt>
					<p>{</p>
					<t>bQlPEk</t>
				</opt>
				<t>ukRs</t>
				<p>@</p>
				<any>
					<n />
					<n h="1509" l="1906" />
					<t>sShpY</t>
					<t>V</t>
				</any>
				<t>Ec</t>
			</opt>
			<t>HpnwzJOy</t>
		</pat>
		<tran>
			<rn v="13820" />
			<var>DCwLIoi</var>
			<rn v="18023" />
			<ltrl>AflSYpVd</ltrl>
			<var>OUoprXsTZ</var>
		</tran>
	</stmt>
</stmset>

=== barzerman/barzer/trantest.xml
<?xml version="1.0" encoding="UTF-8"?>
<stmset xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance"
	xmlns="http://www.barzer.net/barzel/0.1">
	<!--
		for some reason xmllint doesn't like this
		xsi:schemaLocation="http://www.barzer.net/barzel/0.1 barzel.xsd">
	-->
	<stmt>
		<pat>
			<t>China</t><n/><p>/</p>
		</pat>
		<tran>
			<rn>
			<var w="1"/>
			<rn v="56"/>
			</rn> 
			<func name="mkDate"><rn v="9" /><rn v="10" /><rn v="2011" /></func>
		</tran>
	</stmt>
    <stmt>
        <pat>
            <n l="1" h="12"  /><n  l="1" h="31"/><n l="1900" h="2100"/>
        </pat>
        <tran><func name="mkDate"><var w="1" /><var w="2" /><var w="3" /></func></tran>
    </stmt>
</stmset>
